export default function stateinfo(){


const stateData = {
        "alabama": {"mitt_romney": 11, "barack_obama": -12},
        "alaska": {"mitt_romney": 5, "barack_obama": -9},
        "arizona": {"mitt_romney": 4, "barack_obama": -6},
        "arkansas": {"mitt_romney": 11, "barack_obama": -13},
        "california": {"mitt_romney": -12, "barack_obama": 9},
        "colorado": {"mitt_romney": -3, "barack_obama": 1},
        "connecticut": {"mitt_romney": -10, "barack_obama": 8},
        "delaware": {"mitt_romney": -10, "barack_obama": 9},
        "district_of_columbia": {"mitt_romney": -43, "barack_obama": 41},
        "florida": {"mitt_romney": -1, "barack_obama": 0},
        "georgia": {"mitt_romney": 3, "barack_obama": -5},
        "hawaii": {"mitt_romney": -22, "barack_obama": 21},
        "idaho": {"mitt_romney": 15, "barack_obama": -17},
        "illinois": {"mitt_romney": -9, "barack_obama": 7},
        "indiana": {"mitt_romney": 4, "barack_obama": -6},
        "iowa": {"mitt_romney": -4, "barack_obama": 2},
        "kansas": {"mitt_romney": 10, "barack_obama": -12},
        "kentucky": {"mitt_romney": 11, "barack_obama": -12},
        "louisiana": {"mitt_romney": 8, "barack_obama": -9},
        "maine": {"mitt_romney": -9, "barack_obama": 6},
        "maryland": {"mitt_romney": -13, "barack_obama": 12},
        "massachusetts": {"mitt_romney": -12, "barack_obama": 11},
        "michigan": {"mitt_romney": -5, "barack_obama": 4},
        "minnesota": {"mitt_romney": -5, "barack_obama": 3},
        "mississippi": {"mitt_romney": 6, "barack_obama": -6},
        "missouri": {"mitt_romney": 4, "barack_obama": -6},
        "montana": {"mitt_romney": 5, "barack_obama": -8},
        "nebraska": {"mitt_romney": 11, "barack_obama": -12},
        "nevada": {"mitt_romney": -4, "barack_obama": 2},
        "new_hampshire": {"mitt_romney": -4, "barack_obama": 2},
        "new_jersey": {"mitt_romney": -9, "barack_obama": 8},
        "new_mexico": {"mitt_romney": -7, "barack_obama": 3},
        "new_york": {"mitt_romney": -14, "barack_obama": 13},
        "north_carolina": {"mitt_romney": 1, "barack_obama": -2},
        "north_dakota": {"mitt_romney": 9, "barack_obama": -11},
        "ohio": {"mitt_romney": -2, "barack_obama": 0},
        "oklahoma": {"mitt_romney": 17, "barack_obama": -17},
        "oregon": {"mitt_romney": -7, "barack_obama": 4},
        "pennsylvania": {"mitt_romney": -3, "barack_obama": 2},
        "rhode_island": {"mitt_romney": -14, "barack_obama": 13},
        "south_carolina": {"mitt_romney": 5, "barack_obama": -6},
        "south_dakota": {"mitt_romney": 8, "barack_obama": -10},
        "tennessee": {"mitt_romney": 9, "barack_obama": -11},
        "texas": {"mitt_romney": 7, "barack_obama": -9},
        "utah": {"mitt_romney": 23, "barack_obama": -25},
        "vermont": {"mitt_romney": -19, "barack_obama": 17},
        "virginia": {"mitt_romney": -2, "barack_obama": 1},
        "washington": {"mitt_romney": -8, "barack_obama": 6},
        "west_virginia": {"mitt_romney": 12, "barack_obama": -14},
        "wisconsin": {"mitt_romney": -4, "barack_obama": 3},
        "wyoming": {"mitt_romney": 19, "barack_obama": -22},

};

const stateDataString = JSON.stringify(stateData, null, 2);
return stateDataString;
}